// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: olympus/platform/v1/platform.proto

package platformv1connect

import (
	v1 "OlympusGCP-Platform/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/platform/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PlatformServiceName is the fully-qualified name of the PlatformService service.
	PlatformServiceName = "olympus.platform.v1.PlatformService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PlatformServicePushImageProcedure is the fully-qualified name of the PlatformService's PushImage
	// RPC.
	PlatformServicePushImageProcedure = "/olympus.platform.v1.PlatformService/PushImage"
	// PlatformServiceListImagesProcedure is the fully-qualified name of the PlatformService's
	// ListImages RPC.
	PlatformServiceListImagesProcedure = "/olympus.platform.v1.PlatformService/ListImages"
	// PlatformServiceWriteLogProcedure is the fully-qualified name of the PlatformService's WriteLog
	// RPC.
	PlatformServiceWriteLogProcedure = "/olympus.platform.v1.PlatformService/WriteLog"
	// PlatformServiceRecordMetricProcedure is the fully-qualified name of the PlatformService's
	// RecordMetric RPC.
	PlatformServiceRecordMetricProcedure = "/olympus.platform.v1.PlatformService/RecordMetric"
	// PlatformServiceValidateSpecProcedure is the fully-qualified name of the PlatformService's
	// ValidateSpec RPC.
	PlatformServiceValidateSpecProcedure = "/olympus.platform.v1.PlatformService/ValidateSpec"
	// PlatformServiceExecuteBuildProcedure is the fully-qualified name of the PlatformService's
	// ExecuteBuild RPC.
	PlatformServiceExecuteBuildProcedure = "/olympus.platform.v1.PlatformService/ExecuteBuild"
)

// PlatformServiceClient is a client for the olympus.platform.v1.PlatformService service.
type PlatformServiceClient interface {
	// --- Artifact Registry ---
	PushImage(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.StatusResponse], error)
	ListImages(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// --- Cloud Logging & Monitoring ---
	WriteLog(context.Context, *connect.Request[v1.LogRequest]) (*connect.Response[v1.StatusResponse], error)
	RecordMetric(context.Context, *connect.Request[v1.MetricRequest]) (*connect.Response[v1.StatusResponse], error)
	// --- API Gateway (Expansion) ---
	ValidateSpec(context.Context, *connect.Request[v1.SpecRequest]) (*connect.Response[v1.StatusResponse], error)
	// --- Cloud Build (Deepening) ---
	ExecuteBuild(context.Context, *connect.Request[v1.CloudBuildRequest]) (*connect.Response[v1.CloudBuildResponse], error)
}

// NewPlatformServiceClient constructs a client for the olympus.platform.v1.PlatformService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPlatformServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PlatformServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	platformServiceMethods := v1.File_olympus_platform_v1_platform_proto.Services().ByName("PlatformService").Methods()
	return &platformServiceClient{
		pushImage: connect.NewClient[v1.PushRequest, v1.StatusResponse](
			httpClient,
			baseURL+PlatformServicePushImageProcedure,
			connect.WithSchema(platformServiceMethods.ByName("PushImage")),
			connect.WithClientOptions(opts...),
		),
		listImages: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+PlatformServiceListImagesProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListImages")),
			connect.WithClientOptions(opts...),
		),
		writeLog: connect.NewClient[v1.LogRequest, v1.StatusResponse](
			httpClient,
			baseURL+PlatformServiceWriteLogProcedure,
			connect.WithSchema(platformServiceMethods.ByName("WriteLog")),
			connect.WithClientOptions(opts...),
		),
		recordMetric: connect.NewClient[v1.MetricRequest, v1.StatusResponse](
			httpClient,
			baseURL+PlatformServiceRecordMetricProcedure,
			connect.WithSchema(platformServiceMethods.ByName("RecordMetric")),
			connect.WithClientOptions(opts...),
		),
		validateSpec: connect.NewClient[v1.SpecRequest, v1.StatusResponse](
			httpClient,
			baseURL+PlatformServiceValidateSpecProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ValidateSpec")),
			connect.WithClientOptions(opts...),
		),
		executeBuild: connect.NewClient[v1.CloudBuildRequest, v1.CloudBuildResponse](
			httpClient,
			baseURL+PlatformServiceExecuteBuildProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ExecuteBuild")),
			connect.WithClientOptions(opts...),
		),
	}
}

// platformServiceClient implements PlatformServiceClient.
type platformServiceClient struct {
	pushImage    *connect.Client[v1.PushRequest, v1.StatusResponse]
	listImages   *connect.Client[v1.ListRequest, v1.ListResponse]
	writeLog     *connect.Client[v1.LogRequest, v1.StatusResponse]
	recordMetric *connect.Client[v1.MetricRequest, v1.StatusResponse]
	validateSpec *connect.Client[v1.SpecRequest, v1.StatusResponse]
	executeBuild *connect.Client[v1.CloudBuildRequest, v1.CloudBuildResponse]
}

// PushImage calls olympus.platform.v1.PlatformService.PushImage.
func (c *platformServiceClient) PushImage(ctx context.Context, req *connect.Request[v1.PushRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.pushImage.CallUnary(ctx, req)
}

// ListImages calls olympus.platform.v1.PlatformService.ListImages.
func (c *platformServiceClient) ListImages(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.listImages.CallUnary(ctx, req)
}

// WriteLog calls olympus.platform.v1.PlatformService.WriteLog.
func (c *platformServiceClient) WriteLog(ctx context.Context, req *connect.Request[v1.LogRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.writeLog.CallUnary(ctx, req)
}

// RecordMetric calls olympus.platform.v1.PlatformService.RecordMetric.
func (c *platformServiceClient) RecordMetric(ctx context.Context, req *connect.Request[v1.MetricRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.recordMetric.CallUnary(ctx, req)
}

// ValidateSpec calls olympus.platform.v1.PlatformService.ValidateSpec.
func (c *platformServiceClient) ValidateSpec(ctx context.Context, req *connect.Request[v1.SpecRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.validateSpec.CallUnary(ctx, req)
}

// ExecuteBuild calls olympus.platform.v1.PlatformService.ExecuteBuild.
func (c *platformServiceClient) ExecuteBuild(ctx context.Context, req *connect.Request[v1.CloudBuildRequest]) (*connect.Response[v1.CloudBuildResponse], error) {
	return c.executeBuild.CallUnary(ctx, req)
}

// PlatformServiceHandler is an implementation of the olympus.platform.v1.PlatformService service.
type PlatformServiceHandler interface {
	// --- Artifact Registry ---
	PushImage(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.StatusResponse], error)
	ListImages(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// --- Cloud Logging & Monitoring ---
	WriteLog(context.Context, *connect.Request[v1.LogRequest]) (*connect.Response[v1.StatusResponse], error)
	RecordMetric(context.Context, *connect.Request[v1.MetricRequest]) (*connect.Response[v1.StatusResponse], error)
	// --- API Gateway (Expansion) ---
	ValidateSpec(context.Context, *connect.Request[v1.SpecRequest]) (*connect.Response[v1.StatusResponse], error)
	// --- Cloud Build (Deepening) ---
	ExecuteBuild(context.Context, *connect.Request[v1.CloudBuildRequest]) (*connect.Response[v1.CloudBuildResponse], error)
}

// NewPlatformServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPlatformServiceHandler(svc PlatformServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	platformServiceMethods := v1.File_olympus_platform_v1_platform_proto.Services().ByName("PlatformService").Methods()
	platformServicePushImageHandler := connect.NewUnaryHandler(
		PlatformServicePushImageProcedure,
		svc.PushImage,
		connect.WithSchema(platformServiceMethods.ByName("PushImage")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListImagesHandler := connect.NewUnaryHandler(
		PlatformServiceListImagesProcedure,
		svc.ListImages,
		connect.WithSchema(platformServiceMethods.ByName("ListImages")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceWriteLogHandler := connect.NewUnaryHandler(
		PlatformServiceWriteLogProcedure,
		svc.WriteLog,
		connect.WithSchema(platformServiceMethods.ByName("WriteLog")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceRecordMetricHandler := connect.NewUnaryHandler(
		PlatformServiceRecordMetricProcedure,
		svc.RecordMetric,
		connect.WithSchema(platformServiceMethods.ByName("RecordMetric")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceValidateSpecHandler := connect.NewUnaryHandler(
		PlatformServiceValidateSpecProcedure,
		svc.ValidateSpec,
		connect.WithSchema(platformServiceMethods.ByName("ValidateSpec")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceExecuteBuildHandler := connect.NewUnaryHandler(
		PlatformServiceExecuteBuildProcedure,
		svc.ExecuteBuild,
		connect.WithSchema(platformServiceMethods.ByName("ExecuteBuild")),
		connect.WithHandlerOptions(opts...),
	)
	return "/olympus.platform.v1.PlatformService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PlatformServicePushImageProcedure:
			platformServicePushImageHandler.ServeHTTP(w, r)
		case PlatformServiceListImagesProcedure:
			platformServiceListImagesHandler.ServeHTTP(w, r)
		case PlatformServiceWriteLogProcedure:
			platformServiceWriteLogHandler.ServeHTTP(w, r)
		case PlatformServiceRecordMetricProcedure:
			platformServiceRecordMetricHandler.ServeHTTP(w, r)
		case PlatformServiceValidateSpecProcedure:
			platformServiceValidateSpecHandler.ServeHTTP(w, r)
		case PlatformServiceExecuteBuildProcedure:
			platformServiceExecuteBuildHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPlatformServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPlatformServiceHandler struct{}

func (UnimplementedPlatformServiceHandler) PushImage(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.platform.v1.PlatformService.PushImage is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListImages(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.platform.v1.PlatformService.ListImages is not implemented"))
}

func (UnimplementedPlatformServiceHandler) WriteLog(context.Context, *connect.Request[v1.LogRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.platform.v1.PlatformService.WriteLog is not implemented"))
}

func (UnimplementedPlatformServiceHandler) RecordMetric(context.Context, *connect.Request[v1.MetricRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.platform.v1.PlatformService.RecordMetric is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ValidateSpec(context.Context, *connect.Request[v1.SpecRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.platform.v1.PlatformService.ValidateSpec is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ExecuteBuild(context.Context, *connect.Request[v1.CloudBuildRequest]) (*connect.Response[v1.CloudBuildResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.platform.v1.PlatformService.ExecuteBuild is not implemented"))
}
