// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: olympus/platform/v1/platform.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{1}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// Artifact Messages
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{3}
}

func (x *PushRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PushRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Observability Messages
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogName       string                 `protobuf:"bytes,1,opt,name=log_name,json=logName,proto3" json:"log_name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{4}
}

func (x *LogRequest) GetLogName() string {
	if x != nil {
		return x.LogName
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{5}
}

func (x *MetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// API Gateway Messages
type SpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenapiJson   string                 `protobuf:"bytes,1,opt,name=openapi_json,json=openapiJson,proto3" json:"openapi_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecRequest) Reset() {
	*x = SpecRequest{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecRequest) ProtoMessage() {}

func (x *SpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecRequest.ProtoReflect.Descriptor instead.
func (*SpecRequest) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{6}
}

func (x *SpecRequest) GetOpenapiJson() string {
	if x != nil {
		return x.OpenapiJson
	}
	return ""
}

// Cloud Build Messages
type CloudBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildYaml     string                 `protobuf:"bytes,1,opt,name=build_yaml,json=buildYaml,proto3" json:"build_yaml,omitempty"`
	WorkspacePath string                 `protobuf:"bytes,2,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudBuildRequest) Reset() {
	*x = CloudBuildRequest{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudBuildRequest) ProtoMessage() {}

func (x *CloudBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudBuildRequest.ProtoReflect.Descriptor instead.
func (*CloudBuildRequest) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{7}
}

func (x *CloudBuildRequest) GetBuildYaml() string {
	if x != nil {
		return x.BuildYaml
	}
	return ""
}

func (x *CloudBuildRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

type CloudBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LogTail       string                 `protobuf:"bytes,3,opt,name=log_tail,json=logTail,proto3" json:"log_tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudBuildResponse) Reset() {
	*x = CloudBuildResponse{}
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudBuildResponse) ProtoMessage() {}

func (x *CloudBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_platform_v1_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudBuildResponse.ProtoReflect.Descriptor instead.
func (*CloudBuildResponse) Descriptor() ([]byte, []int) {
	return file_olympus_platform_v1_platform_proto_rawDescGZIP(), []int{8}
}

func (x *CloudBuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CloudBuildResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CloudBuildResponse) GetLogTail() string {
	if x != nil {
		return x.LogTail
	}
	return ""
}

var File_olympus_platform_v1_platform_proto protoreflect.FileDescriptor

const file_olympus_platform_v1_platform_proto_rawDesc = "" +
	"\n" +
	"\"olympus/platform/v1/platform.proto\x12\x13olympus.platform.v1\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vListRequest\"$\n" +
	"\fListResponse\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"7\n" +
	"\vPushRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"A\n" +
	"\n" +
	"LogRequest\x12\x19\n" +
	"\blog_name\x18\x01 \x01(\tR\alogName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\rMetricRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"0\n" +
	"\vSpecRequest\x12!\n" +
	"\fopenapi_json\x18\x01 \x01(\tR\vopenapiJson\"Y\n" +
	"\x11CloudBuildRequest\x12\x1d\n" +
	"\n" +
	"build_yaml\x18\x01 \x01(\tR\tbuildYaml\x12%\n" +
	"\x0eworkspace_path\x18\x02 \x01(\tR\rworkspacePath\"b\n" +
	"\x12CloudBuildResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\blog_tail\x18\x03 \x01(\tR\alogTail2\x9b\x04\n" +
	"\x0fPlatformService\x12R\n" +
	"\tPushImage\x12 .olympus.platform.v1.PushRequest\x1a#.olympus.platform.v1.StatusResponse\x12Q\n" +
	"\n" +
	"ListImages\x12 .olympus.platform.v1.ListRequest\x1a!.olympus.platform.v1.ListResponse\x12P\n" +
	"\bWriteLog\x12\x1f.olympus.platform.v1.LogRequest\x1a#.olympus.platform.v1.StatusResponse\x12W\n" +
	"\fRecordMetric\x12\".olympus.platform.v1.MetricRequest\x1a#.olympus.platform.v1.StatusResponse\x12U\n" +
	"\fValidateSpec\x12 .olympus.platform.v1.SpecRequest\x1a#.olympus.platform.v1.StatusResponse\x12_\n" +
	"\fExecuteBuild\x12&.olympus.platform.v1.CloudBuildRequest\x1a'.olympus.platform.v1.CloudBuildResponseBkZiOlympusGCP-Platform/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/platform/v1;platformv1b\x06proto3"

var (
	file_olympus_platform_v1_platform_proto_rawDescOnce sync.Once
	file_olympus_platform_v1_platform_proto_rawDescData []byte
)

func file_olympus_platform_v1_platform_proto_rawDescGZIP() []byte {
	file_olympus_platform_v1_platform_proto_rawDescOnce.Do(func() {
		file_olympus_platform_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_olympus_platform_v1_platform_proto_rawDesc), len(file_olympus_platform_v1_platform_proto_rawDesc)))
	})
	return file_olympus_platform_v1_platform_proto_rawDescData
}

var file_olympus_platform_v1_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_olympus_platform_v1_platform_proto_goTypes = []any{
	(*StatusResponse)(nil),     // 0: olympus.platform.v1.StatusResponse
	(*ListRequest)(nil),        // 1: olympus.platform.v1.ListRequest
	(*ListResponse)(nil),       // 2: olympus.platform.v1.ListResponse
	(*PushRequest)(nil),        // 3: olympus.platform.v1.PushRequest
	(*LogRequest)(nil),         // 4: olympus.platform.v1.LogRequest
	(*MetricRequest)(nil),      // 5: olympus.platform.v1.MetricRequest
	(*SpecRequest)(nil),        // 6: olympus.platform.v1.SpecRequest
	(*CloudBuildRequest)(nil),  // 7: olympus.platform.v1.CloudBuildRequest
	(*CloudBuildResponse)(nil), // 8: olympus.platform.v1.CloudBuildResponse
}
var file_olympus_platform_v1_platform_proto_depIdxs = []int32{
	3, // 0: olympus.platform.v1.PlatformService.PushImage:input_type -> olympus.platform.v1.PushRequest
	1, // 1: olympus.platform.v1.PlatformService.ListImages:input_type -> olympus.platform.v1.ListRequest
	4, // 2: olympus.platform.v1.PlatformService.WriteLog:input_type -> olympus.platform.v1.LogRequest
	5, // 3: olympus.platform.v1.PlatformService.RecordMetric:input_type -> olympus.platform.v1.MetricRequest
	6, // 4: olympus.platform.v1.PlatformService.ValidateSpec:input_type -> olympus.platform.v1.SpecRequest
	7, // 5: olympus.platform.v1.PlatformService.ExecuteBuild:input_type -> olympus.platform.v1.CloudBuildRequest
	0, // 6: olympus.platform.v1.PlatformService.PushImage:output_type -> olympus.platform.v1.StatusResponse
	2, // 7: olympus.platform.v1.PlatformService.ListImages:output_type -> olympus.platform.v1.ListResponse
	0, // 8: olympus.platform.v1.PlatformService.WriteLog:output_type -> olympus.platform.v1.StatusResponse
	0, // 9: olympus.platform.v1.PlatformService.RecordMetric:output_type -> olympus.platform.v1.StatusResponse
	0, // 10: olympus.platform.v1.PlatformService.ValidateSpec:output_type -> olympus.platform.v1.StatusResponse
	8, // 11: olympus.platform.v1.PlatformService.ExecuteBuild:output_type -> olympus.platform.v1.CloudBuildResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_olympus_platform_v1_platform_proto_init() }
func file_olympus_platform_v1_platform_proto_init() {
	if File_olympus_platform_v1_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_olympus_platform_v1_platform_proto_rawDesc), len(file_olympus_platform_v1_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olympus_platform_v1_platform_proto_goTypes,
		DependencyIndexes: file_olympus_platform_v1_platform_proto_depIdxs,
		MessageInfos:      file_olympus_platform_v1_platform_proto_msgTypes,
	}.Build()
	File_olympus_platform_v1_platform_proto = out.File
	file_olympus_platform_v1_platform_proto_goTypes = nil
	file_olympus_platform_v1_platform_proto_depIdxs = nil
}
